### ISSUE TITLE
AWS Assume Role

### ISSUE THREAD

**Issue by fabge** [leonstafford/wp2static-addon-s3#42]
Hello,

I’d like to publish the static content of a WordPress site to an AWS S3 bucket.

In our company, we have some restrictions in the AWS cloud accounts. One of them is, that the user can only assume a role. Only the role then gives the user permissions to e.g. upload to S3.

Unfortunately the ‘assume role’ concept is not built into WP2Static, eventhough this pattern is quite common.

Are there any workarounds?

Best
Fabian

**Comment by leonstafford** [comment]
should be working fine for some time now. please let me know if still facing issues using instance role
